---
- name: stop psql
  systemd:
    name: postgresql
    state: stop

- name: disable psql
  systemd:
    name: postgresql
    enabled: no

- name: restart keepalived
  service:
    name: keepalived
    state: restarted

- name: restart haproxy
  service:
    name: haproxy
    state: restarted

- name: restart etcd
  service:
    name: etcd
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart patroni
  systemd:
    name: patroni
    state: restarted
